# Generated by Django 5.0.1 on 2024-01-10 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_user_user_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_profile',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_registration_date',
            new_name='registration_date',
        ),
    ]
